apiVersion: v1
kind: Service
metadata:
  name: financial-assistant-service
spec:
  type: LoadBalancer
  selector:
    app: financial-assistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501